### ISSUE TITLE
Get rid of the BILT 2019 default image and text since it is over

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#12]

**Comment by theo-armour** [comment]
Gone as of v0.16.06

https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/

**Comment by StephenRoth2014** [comment]
The "BILT EUR 2019" model is still the default model. I'd prefer the original default model. Thanks.

**Comment by theo-armour** [comment]
@StephenRoth2014 

See   Spider gbXML Viewer 'Maevia' 0.17.07-3. The clifton downs file is reset as the default file. The BiLT file is still available from the Spider samples files menu
