### ISSUE TITLE
gbXML viewer does not display well on a smartphone (iPhone specifically)

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#2]
There's a couple of issues with the viewer on a smartphone (iPhone, specifically):

1. The pop-up menus are too big and unwieldy. They should, by default, be minimized on start. 
2. The pop-up menu on the left appears non-opaque against the screen background so it is hard to read the text (at least on the iPhone)
3. I selected one surface to display in the model, but could not figure out how to reset the view so as to view the entire model again.
4. Is there a way to upload gbXML files when using a smartphone or tablet?
5. The buttons in the title bar of the pop-up menu do not appear to work on the smartphone

![Image-1](https://user-images.githubusercontent.com/8326316/65272134-6214dd80-dad3-11e9-8b9b-253bc803fcf9.jpg)
![Image-1 (1)](https://user-images.githubusercontent.com/8326316/65272135-6214dd80-dad3-11e9-8787-81e9617ed89d.jpg)

**Comment by theo-armour** [comment]
Got it. Will fix.

**Comment by theo-armour** [comment]
@StephenRoth2014 

Sorry for the delay. Here is what v0.17,03-05 looks like in my JavaScript console. Menu needs much sliding around in portrait mode but it looks like it still kind of works on an iPhone SE. Anyway, needs testing on real devices.

![image](https://user-images.githubusercontent.com/547626/65364784-bf3e8b00-dbc8-11e9-984d-9e27a47947a8.png)

**Comment by StephenRoth2014** [comment]
@theo-armour Minimize pop-up on start.

**Comment by theo-armour** [comment]
@StephenRoth2014 
in: https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/

![image](https://user-images.githubusercontent.com/547626/65733141-1ee1de00-e082-11e9-8bdf-3c47c9fd90cb.png)

Getting there. Need to work on icons reflowing out of their box

Note that moving slider or 'hamburger button to bottom on mobile is a trend

* https://www.smashingmagazine.com/2019/08/bottom-navigation-pattern-mobile-web-pages/
* https://uxmovement.com/mobile/why-mobile-menus-belong-at-the-bottom-of-the-screen/

**Comment by theo-armour** [comment]
in: https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/

beginning to settle down maybe

![image](https://user-images.githubusercontent.com/547626/65810409-f7147800-e15e-11e9-9b91-53ac5c8f9e49.png)

**Comment by StephenRoth2014** [comment]
Ok
