### ISSUE TITLE
The "Help" question mark hyperlinks take user to generic help

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#5]
When I click on the help icons, generic text is displayed in the pop-up form and not appropriate context-sensitive help.
![2](https://user-images.githubusercontent.com/8326316/65636429-1bbdf380-df97-11e9-9fa8-3f49cd19ee3d.PNG)

**Comment by theo-armour** [comment]
@StephenRoth2014 

I can't seem to reproduce the error. Sometimes an error that happened earlier can have downstream unintended consequences.

In any case, the whole help thing needs reviewing
