### ISSUE TITLE
I like certain aspects of the cleaner look of version 14 of the viewer.

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#6]
For example, the pop-up form in V14 that displays element characteristics is cleaner and also I like the list of all elements in the listbox.

Let's discuss
![3](https://user-images.githubusercontent.com/8326316/65636545-5a53ae00-df97-11e9-9e6a-9e1f2fe616e2.PNG)

**Comment by theo-armour** [comment]
R14 sets the "Cosmo" Bootswatch theme as the default.

We can do this again with v0.17 but it takes a fair amount of tweaking to get things just right, so it should be done after the UI is quite settled. In any case there are a bunch of issues with theming and I will be revising these as part of the nice UX effort.

We might also consider building a custom "Green Building" theme. ;-)
