### ISSUE TITLE
The text in the pop-ups should be smaller (like V14). It looks cleaner that way.

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#7]
![4](https://user-images.githubusercontent.com/8326316/65636775-d5b55f80-df97-11e9-9fcd-23bd0300408f.PNG)

**Comment by theo-armour** [comment]
@StephenRoth2014 

Done

See dev release

**Comment by StephenRoth2014** [comment]
Ok
