### ISSUE TITLE
In the gbXML samples menu, the categories should be better organized and more descriptive

### ISSUE THREAD

**Issue by StephenRoth2014** [GreenBuildingXML/GreenBuildingXML.github.io#8]
The gbXML sample categories should be simpler and more descriptive:

1. Combine 2 and 3
2. Get rid of 5
3. What is "Build Well"? Rename to something else.
![6](https://user-images.githubusercontent.com/8326316/65638547-372afd80-df9b-11e9-9153-ba3bcb3fcbb3.PNG)

**Comment by theo-armour** [comment]
![image](https://user-images.githubusercontent.com/547626/65810701-7a839880-e162-11e9-9321-9b7770b1bc44.png)

https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/dev/

* Fixed a bug where the full description text was not being shown
* Added text and links to each each
* Added intro sentence to the menu
